USE [master]
GO

/****** Object:  Database [HRMS]    Script Date: 11/1/2022 1:50:11 AM ******/
CREATE DATABASE [HRMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HRMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MARS\MSSQL\DATA\HRMS.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HRMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MARS\MSSQL\DATA\HRMS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HRMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HRMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HRMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HRMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HRMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [HRMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HRMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HRMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HRMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HRMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HRMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HRMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HRMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HRMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HRMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HRMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HRMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HRMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HRMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HRMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HRMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HRMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HRMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HRMS] SET  MULTI_USER 
GO

ALTER DATABASE [HRMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HRMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HRMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HRMS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HRMS] SET  READ_WRITE 
GO



USE [HRMS]
GO

/****** Object:  Table [dbo].[City]    Script Date: 11/1/2022 2:40:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[City](
	[CityId] [int] IDENTITY(1,1) NOT NULL,
	[StateId] [int] NOT NULL,
	[CityName] [varchar](100) NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[CityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[City]  WITH CHECK ADD  CONSTRAINT [FK_City_States] FOREIGN KEY([StateId])
REFERENCES [dbo].[States] ([StateId])
GO

ALTER TABLE [dbo].[City] CHECK CONSTRAINT [FK_City_States]
GO

USE [HRMS]
GO

/****** Object:  Table [dbo].[Country]    Script Date: 11/1/2022 2:40:23 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Country](
	[CountryId] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [varchar](100) NULL,
 CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED 
(
	[CountryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [HRMS]
GO

/****** Object:  Table [dbo].[Locations]    Script Date: 11/1/2022 2:40:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Locations](
	[LocId] [int] IDENTITY(1,1) NOT NULL,
	[OrgId] [int] NOT NULL,
	[Address] [varchar](200) NULL,
	[CountryId] [int] NULL,
	[CityId] [int] NULL,
	[StateId] [int] NULL,
 CONSTRAINT [PK_Locations] PRIMARY KEY CLUSTERED 
(
	[LocId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Locations]  WITH CHECK ADD  CONSTRAINT [FK_Locations_Organization] FOREIGN KEY([OrgId])
REFERENCES [dbo].[Organization] ([OrgId])
GO

ALTER TABLE [dbo].[Locations] CHECK CONSTRAINT [FK_Locations_Organization]
GO

USE [HRMS]
GO

/****** Object:  Table [dbo].[Organization]    Script Date: 11/1/2022 2:41:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Organization](
	[OrgId] [int] IDENTITY(1,1) NOT NULL,
	[OrgName] [varchar](100) NULL,
	[Logo] [varchar](100) NULL,
	[ContactNo] [varchar](50) NULL,
	[EmailAddress] [varchar](100) NULL,
	[CountryId] [int] NULL,
 CONSTRAINT [PK_Organization] PRIMARY KEY CLUSTERED 
(
	[OrgId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Organization]  WITH CHECK ADD  CONSTRAINT [FK_Organization_Country] FOREIGN KEY([CountryId])
REFERENCES [dbo].[Country] ([CountryId])
GO

ALTER TABLE [dbo].[Organization] CHECK CONSTRAINT [FK_Organization_Country]
GO

USE [HRMS]
GO

/****** Object:  Table [dbo].[States]    Script Date: 11/1/2022 2:41:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[States](
	[StateId] [int] IDENTITY(1,1) NOT NULL,
	[CountryId] [int] NOT NULL,
	[StateName] [varchar](100) NULL,
 CONSTRAINT [PK_States] PRIMARY KEY CLUSTERED 
(
	[StateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[States]  WITH CHECK ADD  CONSTRAINT [FK_States_Country] FOREIGN KEY([CountryId])
REFERENCES [dbo].[Country] ([CountryId])
GO

ALTER TABLE [dbo].[States] CHECK CONSTRAINT [FK_States_Country]
GO








